version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      
artifacts:
  type: zip
  files:
    - dulwich/**/*
    - dulwich-0.18.6.egg-info/**/*
    - pipeline-lambda-draft.py
