
version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - dulwich dulwich-0.18.6.egg-info pipeline-lambda-draft.py
      - ls -a
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dulwich/**/*
    - dulwich-0.18.6.egg-info/**/*
    - pipeline-lambda-draft.py
