
version: 0.2

phases:
  install: 
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install zip -y
      - echo installed zip successfully
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - zip dulwich dulwich-0.18.6.egg-info pipeline-lambda-draft.py
      - ls -a
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - dulwich.zip
